dependencies {
	testIntegrationCompile group: "com.liferay.portal", name: "com.liferay.portal.impl", version: "default"
	testIntegrationCompile group: "javax.portlet", name: "portlet-api", version: "3.0.1"
	testIntegrationCompile group: "org.apache.felix", name: "org.apache.felix.http.servlet-api", version: "1.1.2"
	testIntegrationCompile group: "org.osgi", name: "org.osgi.service.cm", version: "1.6.0"
	testIntegrationCompile project(":apps:feature-flag:feature-flag-api")
	testIntegrationCompile project(":apps:xstream:xstream-configurator-api")
	testIntegrationCompile project(":core:osgi-service-tracker-collections")
	testIntegrationCompile project(":test:arquillian-extension-junit-bridge")
}